# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Home Assistant Locator
version: "0.1.0"
slug: ha_locator
description: Add-on to locate your devices
url: "https://github.com/diegoaugustus/ha-locator"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
startup: "application"
boot: "auto"
options: {}
schema: {}
