# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Home Assistant Locator
version: "0.1.10"
slug: ha_locator
description: Add-on to locate your devices
url: "https://github.com/diegoaugustus/ha-locator"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services
options:
  mqtt_user: !secret mqtt_username
  mqtt_password: !secret mqtt_password
schema:
  mqtt_user: str
  mqtt_password: str
